dist: trusty
language: python
python:
- 3.4_with_system_site_packages
before_install:
- sudo apt-get update
- sudo apt-get install python3-all-dev debhelper python3-setuptools python3-pip apt-file fakeroot
  pyqt5-dev-tools qttools5-dev-tools qt4-dev-tools
- sudo pip3 install stdeb
install:
- which python3
- which pip3
- pip3 --version
- python3 -c "import sys; print(sys.version)"
- python3 setup.py build
- python3 setup.py --command-packages=stdeb.command bdist_deb
- for f in deb_dist/*.deb; do echo; echo $f; dpkg --contents $f; done
- sudo dpkg -i deb_dist/*.deb
script:
- which vscode-launcher-tray
- dpkg -L python3-vscode-launcher-tray
before_deploy:
  - export RELEASE_DEB_FILE=$(ls deb_dist/*.deb)
  - echo "deploying $RELEASE_DEB_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: "VLUcB5UGrNVfbhPmhNS+UsIz7jzgyUqV6p+N5ovpQCAqfeIkCJP6lwFoe5/RDIp/keGZ7KW9MuYidc+2m9COt9QJOvFDJ3MRNFPt32+YWBgK8Mz01djXF2NBtNnKZ+rUlTwWQ2MqXyVU3zcNxIkN9UHWFWFKbgoNssS4YdSEt6dn0t7V9WAZx4k3sPrzlazVIkiHPg+WB66FAN7/+Auf0Vyv1PMHUnO3U6JwQXBpEPIutOp6257GPzIVQxRtlEnPxU/NoXizCQAMfhBmlq0SFZARtHwIRgEhdPxThpQhonQmBa0Xwa3EcSA+S9KYD1gDHvWEbQHlWd5rzukqg957YBiF33vT3NpQCA4aTl/7nQp5jf99Z5zRFZv6HY0CPuSx+eVclwtmkaGFIcvLPcv6JwjeHYythc3c++UaaH1fEEeHW8DmOjqIZWdowGXvMjNnK2LqfwJ6/NVBMFN+pzneVE2P23Tm/AZ3gJLzZZ8ZKpOdWJqjeIqgkDcW5W4tV2lB6splSg3v4tTB/Qw79OJxHHstXYq3p+iPifQKKe3TrPW4nn8FnG4uwhljKqeGM1OQP2ps9vnKe4dqHcAKXsRmfs7oTBdbAW1oeaIvUQ5oIdOk6mDEAUTGSL7XDoEThIqwzr/t4o0gI6uUwQxBGmAB24qnX3L29yQ2lkYSJTC4Z3k="
  file: "${RELEASE_DEB_FILE}"
  skip_cleanup: true
  overwrite: true
  on:
    repo: elleryq/vscode-launcher-tray
    tags: true
