dist: trusty
language: python
python:
    - "3.4_with_system_site_packages"
before_install:
    - sudo apt-get update
    - sudo apt-get install python3-all-dev debhelper python3-setuptools python3-pip apt-file
    - sudo pip3 install stdeb
install:
    - which python3
    - which pip3
    - pip3 --version
    - python3 -c "import sys; print(sys.version)"
    # Build a .deb file and then install it.
    - python3 setup.py --command-packages=stdeb.command bdist_deb
    - for f in deb_dist/*.deb; do echo; echo $f; dpkg --contents $f; done
    - sudo dpkg -i deb_dist/*.deb
