dist: xenial
language: python
python:
- 3.5_with_system_site_packages
before_install:
- sudo -H apt-get update
- sudo -H apt-get install python3-all-dev debhelper python3-setuptools python3-pip apt-file
  fakeroot pyqt5-dev-tools qttools5-dev-tools qt4-dev-tools xdg-utils python3-xdg
- sudo -H pip3 install stdeb3
install:
- which python3
- which pip3
- pip3 --version
- python3 -c "import sys; print(sys.version)"
- python3 setup.py build
- python3 setup.py --command-packages=stdeb3.command bdist_deb
- for f in deb_dist/*.deb; do echo; echo $f; dpkg --contents $f; done
- sudo -H dpkg -i deb_dist/*.deb
script:
- which vscode-launcher-tray
- dpkg -L python3-vscode-launcher-tray
before_deploy:
- export RELEASE_DEB_FILE=$(ls deb_dist/*.deb)
- echo "deploying $RELEASE_DEB_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: aWb7Qscnzp24cJFS3yAhTRKY6qS9xr0R1JttIsjtpOMUi3oW0afBm20zfOJLmG+1wt8X7QpBHZgk2nk/woYhD7/rD2w5Hb4DMvYlKoUZ+c1P63Hy+AIhZ4ZFLQ0diQbp5QX9+0PE9iOpG1O31qzODKKDXOgRRqN7cVv1GUBO1TM7YVQoOG3tDWHywTdyJ/2KXVTT1ZoTSPELokxM8APSNJBRiDzRMnwoo2QKv/55D25wRJ2P5OJkeWP35E8AWYdkNifbg0FYugfZnNqwPmQLoOBDJVLQp9Vmu1+o4fJkfAabKtIZXJGjFS/bkjIIHj34p84ZfvL7TVISf/h9DVEsrxmujmKqFu9InE3EFFWTKhbFPzAwBFODZpkxAwKWBdvIC6R+4iX0qAOSmYaNBvBOITNjv86/Fe82CkYvMr6uCNNWc/ZKeBhIoUzSkxJ4tNerJ1HqdG7H525JD+SJ6oc5BRo7BLj6cJeoCS9EHiErgw6CBu7URkXiRRoknl28SUoA6+ZoaW5MnlYRKlAzY/dfOb3RHPN0bP4wgFHZjcqZx5FUMwDU6k18V9WkQP2vWf4Zagncwb2HbtNkLIfCPDHP4ilbYJTuStaqy+hMlpvsaneKZRZ4IUv6cnA5u+sQNddlRiCEBodZ3sh4tafokyEGCCFui+I6/RPWm31UM0RVGys=
  file: "${RELEASE_DEB_FILE}"
  skip_cleanup: true
  overwrite: true
  on:
    repo: elleryq/vscode-launcher-tray
    tags: true
